Repository ti-community-infra/tichi, pull requests merged in 2020-11, with the labels that each got.

#87 config: enable for tikv pd
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#88 build: bump version to v20201102-45eeca6478
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/config/config.yaml
Labels: size/M, status/can-merge

#89 config: use branch protection
  configs/prow/config/config.yaml
Labels: size/M, status/can-merge

#92 fix: remove useless `no-issue`
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: size/M, status/can-merge

#93 feat: impl ti community needs rebase
  .goreleaser.yml
  cmd/ticommunityneedsrebase/main.go
  deployments/plugins/needsrebase/Dockerfile
  internal/pkg/externalplugins/needsrebase/needsrebase.go
Labels: size/XL, status/can-merge

#94 fix: refine interrupts
  cmd/ticommunityneedsrebase/main.go
Labels: size/S, status/can-merge

#95 fix: support github update
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: size/L, status/can-merge

#96 fix: refine typo
  internal/pkg/externalplugins/merge/merge.go
Labels: size/XS, status/can-merge

#97 fix: store last commit hash
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: size/M, status/can-merge

#98 config: bump version
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/XS, status/can-merge

#99 config: add pingcap community repo
  configs/prow/cluster/label_sync.yaml
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/labels.yaml
  configs/prow/config/plugins.yaml
Labels: size/L, status/can-merge

#100 config: enable branch protection for tikv/pd
  configs/prow/config/config.yaml
Labels: size/S, status/can-merge

#101 config: add strict check
  configs/prow/config/config.yaml
Labels: size/XS, status/can-merge

#102 docs: finish the ti-community-owners
  .DS_Store
  .github/workflows/gh-pages.yml
  .github/workflows/preview.yml
  docs/.gitignore
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/chapter_1.md
  docs/src/components.md
  docs/src/components/tide.md
  docs/src/introduction.md
  docs/src/plugins.md
  docs/src/plugins/label.md
  docs/src/plugins/lgtm.md
  docs/src/plugins/merge.md
  docs/src/plugins/owners.md
  docs/src/workflows.md
  docs/src/workflows/.keep
Labels: size/L

#103 ci: fix preview
  .github/workflows/preview.yml
Labels: size/XS, status/can-merge

#104 build: bump the version
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/config/config.yaml
Labels: size/M, status/can-merge

#105 config: add required-contexts for pd
  configs/prow/config/config.yaml
Labels: size/S, status/can-merge

#106 docs: finish lgtm
  docs/src/components/tide.md
  docs/src/introduction.md
  docs/src/plugins/lgtm.md
  docs/src/plugins/owners.md
Labels: size/L, status/can-merge

#108 feat: support require lgtm for owners
  docs/src/plugins/owners.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/L, status/can-merge

#109 feat: impl autoresponder
  .goreleaser.yml
  cmd/ticommunityautoresponder/main.go
  deployments/plugins/autoresponder/Dockerfile
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/autoresponder/autoresponder_test.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
Labels: size/XXL

#110 fix: use simple response
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_autoresponder_service.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
  internal/pkg/externalplugins/autoresponder/autoresponder.go
Labels: size/M, status/can-merge

#111 fix: rename approver be committer
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/config/labels.yaml
  docs/src/plugins/owners.md
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/ownersclient/ownersclient_test.go
  internal/pkg/ownersclient/types.go
Labels: size/L, status/can-merge

#112 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/S, status/can-merge

#113 docs: finish merge and label
  .github/workflows/preview.yml
  .github/workflows/rebase.yml
  docs/src/plugins/label.md
  docs/src/plugins/lgtm.md
  docs/src/plugins/merge.md
Labels: size/L

#114 docs: finish pr workflow
  .github/workflows/preview.yml
  docs/src/SUMMARY.md
  docs/src/drawios/pr-workflow.drawio
  docs/src/pr-workflow.png
  docs/src/workflows.md
  docs/src/workflows/.keep
  docs/src/workflows/label.md
  docs/src/workflows/pr.md
Labels: size/M

#115 docs: fix typo
  docs/src/workflows/pr.md
Labels: size/XS

#116 ci: add caname
  .github/workflows/gh-pages.yml
Labels: size/XS

#117 ci: add config check
  .prow.yaml
  configs/prow/config/config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#118 chore: remove doc link
  .prow.yaml
  README.md
  configs/prow/config/config.yaml
Labels: size/M, status/can-merge

#119 config: add responder and require LGTM prefix to pd
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#120 config: add new line for pd responder
  configs/prow/config/external_plugins_config.yaml
Labels: size/XS, status/can-merge

#121 build: bump version
  .github/workflows/release.yml
  .github/workflows/test.yml
  .prow.yaml
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/config/config.yaml
  go.mod
  go.sum
Labels: size/M, status/can-merge

#122 fix: support set default require lgtm
  docs/src/plugins/owners.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/M, status/can-merge

#123 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/S, status/can-merge

#124 config: enable bot for tidb-dashboard
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/can-merge

#125 feat: impl blunderbuss
  .goreleaser.yml
  cmd/ticommunityblunderbuss/main.go
  deployments/plugins/blunderbuss/Dockerfile
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
Labels: size/XXL, status/can-merge

#127 config: enable blunderbuss for pd
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#130 fix: use pr last commit sha
  internal/pkg/externalplugins/tars/tars.go
Labels: size/XS, status/can-merge

#131 build: bump prow github
  go.mod
  go.sum
Labels: size/XS, status/can-merge

#132 config: deploy tars
  configs/prow/cluster/ti_community_tars_deployment.yaml
  configs/prow/cluster/ti_community_tars_service.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/can-merge

#133 chore: remove .DS_Store
  .DS_Store
Labels: size/XS, status/can-merge

#134 fix: use external plugin message
  internal/pkg/externalplugins/respond.go
  internal/pkg/externalplugins/tars/tars.go
Labels: size/XS, status/can-merge

#135 build: bump the version
  go.mod
  go.sum
Labels: size/XS, status/can-merge

#137 build: bump deps version
  .prow.yaml
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/config/config.yaml
  configs/prow/config/plugins.yaml
  go.mod
  go.sum
Labels: size/M, status/can-merge

#138 config: use peribolos sync team
  configs/prow/cluster/peribolos.yaml
  configs/prow/cluster/prow_controller_manager_rbac.yaml
  configs/prow/cluster/sinker_rbac.yaml
  configs/prow/config/config.yaml
Labels: size/L, status/can-merge

#139 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/S, status/can-merge

#140 feat: tars support scan prs
  cmd/ticommunitytars/main.go
  go.mod
  internal/pkg/externalplugins/tars/tars.go
Labels: size/L, status/can-merge

#141 fix: refine pull request type
  configs/prow/cluster/ti_community_tars_deployment.yaml
  internal/pkg/externalplugins/tars/tars.go
Labels: size/M, status/can-merge

#142 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/can-merge

#143 test: add test for tars
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/XL, status/can-merge

#145 feat: support tars configuration
  cmd/ticommunitytars/main.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/XL, status/can-merge

#146 fix: refine external plugin config path
  cmd/ticommunitytars/main.go
Labels: size/XS, status/can-merge

#148 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_tars_deployment.yaml
  configs/prow/config/external_plugins_config.yaml
Labels: size/S, status/can-merge

#150 feat: tars support OnlyWhenLabel configuration
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/L, status/can-merge

#151 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/can-merge

#149 config: enable tars for pd
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#152 config: migrate dashboard into pingcap org
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#154 fix: update help provider configuration everytime
  cmd/ticommunityautoresponder/main.go
  cmd/ticommunityblunderbuss/main.go
  cmd/ticommunitylabel/main.go
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/autoresponder/autoresponder_test.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: size/M, status/can-merge

#155 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/can-merge

#157 fix: only push and admin collaborator can lgtm and merge non sig label PR
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/L, status/can-merge

#158 build: bump version
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/can-merge

#159 config: only require one lgtm for tidb-community-bots
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
Labels: size/XS, status/can-merge

#160 config: enable blunderbuss for other tidb-community-bots repos
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
Labels: size/S, status/can-merge

#161 config: fix wrong config
  configs/prow/cluster/peribolos.yaml
  configs/prow/config/config.yaml
Labels: size/XS, status/can-merge

#162 docs: add more details for lgtm
  docs/src/plugins/lgtm.md
Labels: size/M, status/LGT1, status/can-merge

#163 config: enable more plugins for tidb-community-bots org repos
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/LGT1, status/can-merge

#164 config: remove configs
  .gitignore
  .prow.yaml
  configs/prow/Makefile
  configs/prow/README.md
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/crier_rbac.yaml
  configs/prow/cluster/crier_service.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/deck_rbac.yaml
  configs/prow/cluster/deck_service.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/hook_rbac.yaml
  configs/prow/cluster/hook_service.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/horologium_rbac.yaml
  configs/prow/cluster/horologium_service.yaml
  configs/prow/cluster/ing_ingress.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/needs-rebase_service.yaml
  configs/prow/cluster/peribolos.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/plank_rbac.yaml
  configs/prow/cluster/plank_service.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/prow_controller_manager_rbac.yaml
  configs/prow/cluster/prow_controller_manager_service.yaml
  configs/prow/cluster/prow_namespace.yaml
  configs/prow/cluster/prowjob_customresourcedefinition.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/sinker_rbac.yaml
  configs/prow/cluster/sinker_service.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/statusreconciler_rbac.yaml
  configs/prow/cluster/test-pods_namespace.yaml
  configs/prow/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow/cluster/ti_community_autoresponder_service.yaml
  configs/prow/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow/cluster/ti_community_blunderbuss_service.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_label_service.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_service.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_merge_service.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_owners_service.yaml
  configs/prow/cluster/ti_community_tars_deployment.yaml
  configs/prow/cluster/ti_community_tars_service.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/cluster/tide_rbac.yaml
  configs/prow/cluster/tide_service.yaml
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/labels.yaml
  configs/prow/config/plugins.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#167 config: add prow dev cluster configs
  configs/prow-dev/.gitignore
  configs/prow-dev/Makefile
  configs/prow-dev/README.md
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/crier_rbac.yaml
  configs/prow-dev/cluster/crier_service.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/deck_rbac.yaml
  configs/prow-dev/cluster/deck_service.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/hook_rbac.yaml
  configs/prow-dev/cluster/hook_service.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/horologium_rbac.yaml
  configs/prow-dev/cluster/horologium_service.yaml
  configs/prow-dev/cluster/ing_ingress.yaml
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/needs-rebase_service.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/plank_rbac.yaml
  configs/prow-dev/cluster/plank_service.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_rbac.yaml
  configs/prow-dev/cluster/prow_controller_manager_service.yaml
  configs/prow-dev/cluster/prow_namespace.yaml
  configs/prow-dev/cluster/prowjob_customresourcedefinition.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/sinker_rbac.yaml
  configs/prow-dev/cluster/sinker_service.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_rbac.yaml
  configs/prow-dev/cluster/test-pods_namespace.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_service.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_service.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_service.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_service.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_service.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_service.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_service.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/cluster/tide_rbac.yaml
  configs/prow-dev/cluster/tide_service.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/labels.yaml
  configs/prow-dev/config/plugins.yaml
Labels: size/XXL, status/can-merge

#165 fix: get pull request only once
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/L, status/LGT1, status/can-merge

#169 build: bump the version
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/M, status/can-merge

#171 ci: fix preview job
  .github/workflows/preview.yml
Labels: size/XS, status/can-merge

#172 ci: fix preview push job
  .github/workflows/preview.yml
Labels: size/XS, status/can-merge

#170 docs: add tars doc and update workflow
  .gitignore
  docs/src/SUMMARY.md
  docs/src/components/tide.md
  docs/src/introduction.md
  docs/src/plugins/blunderbuss.md
  docs/src/plugins/label.md
  docs/src/plugins/lgtm.md
  docs/src/plugins/merge.md
  docs/src/plugins/owners.md
  docs/src/plugins/tars.md
  docs/src/workflows/pr.md
Labels: size/L, status/LGT1, status/can-merge

#173 ci: add deploy job
  .prow.yaml
  configs/prow-dev/Makefile
  scripts/deploy.sh
Labels: size/L, status/LGT1, status/can-merge

#174 feat: init web bolierplate
  web/.gitignore
  web/README.md
  web/components/header/index.tsx
  web/next-env.d.ts
  web/next.config.js
  web/package.json
  web/pages/_app.tsx
  web/pages/api/hello.js
  web/pages/index.tsx
  web/public/favicon.ico
  web/public/vercel.svg
  web/styles/globals.css
  web/styles/home.module.scss
  web/tsconfig.json
Labels: size/L, status/LGT1, status/can-merge
