Repository ti-community-infra/tichi, pull requests merged in 2020-10, with the labels that each got.

#3 build: add external plugins config
  Makefile
  cluster/ti_community_lgtm_deployment.yaml
  cluster/ti_community_lgtm_service.yaml
  config/external_plugins_config.yaml
  config/plugin.yaml
Labels: status/can-merge

#6 feat: add ti-community-merge configs
  config/config.yaml
  config/plugin.yaml
Labels: status/can-merge

#7 feat: add pkgs
  .gitattributes
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .golangci.yml
  .goreleaser.yml
  LICENSE
  Makefile
  README.md
  configs/prow/Makefile
  configs/prow/README.md
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/crier_rbac.yaml
  configs/prow/cluster/crier_service.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/deck_rbac.yaml
  configs/prow/cluster/deck_service.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/hook_rbac.yaml
  configs/prow/cluster/hook_service.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/horologium_rbac.yaml
  configs/prow/cluster/horologium_service.yaml
  configs/prow/cluster/ing_ingress.yaml
  configs/prow/cluster/minio.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/prow_controller_manager_rbac.yaml
  configs/prow/cluster/prow_controller_manager_service.yaml
  configs/prow/cluster/prow_namespace.yaml
  configs/prow/cluster/prowjob_customresourcedefinition.yaml
  configs/prow/cluster/s3_secrets.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/sinker_rbac.yaml
  configs/prow/cluster/sinker_service.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/statusreconciler_rbac.yaml
  configs/prow/cluster/test-pods_namespace.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_service.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/cluster/tide_rbac.yaml
  configs/prow/cluster/tide_service.yaml
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugin.yaml
  go.mod
  go.sum
  pkg/externalplugins/config.go
  pkg/externalplugins/config_test.go
  pkg/externalplugins/plugins.go
  pkg/externalplugins/plugins_test.go
  pkg/externalplugins/respond.go
  pkg/externalplugins/respond_test.go
  pkg/reviewersclient/reviewersclient.go
  pkg/reviewersclient/reviewersclient_test.go
  tools/check/check-tidy.sh
Labels: status/can-merge

#8 chore: refine README.md
  README.md
  configs/prow/README.md
Labels: status/can-merge

#9 chore: add badges
  README.md
Labels: status/can-merge

#10 chore: remove tidb-community-bots/ti-prow-external-plugins-config
  .github/semantic.yml
  configs/prow/config/config.yaml
  configs/prow/config/plugin.yaml
Labels: status/can-merge

#11 test: add more cases bb4465a
  go.mod
  go.sum
  pkg/externalplugins/config_test.go
Labels: status/can-merge

#12 feat: add owners client
  .codecov.yml
  README.md
  configs/prow/config/external_plugins_config.yaml
  pkg/externalplugins/config.go
  pkg/externalplugins/config_test.go
  pkg/externalplugins/plugins.go
  pkg/externalplugins/plugins_test.go
  pkg/ownersclient/ownersclient.go
  pkg/ownersclient/ownersclient_test.go
  pkg/reviewersclient/reviewersclient.go
  pkg/reviewersclient/reviewersclient_test.go
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
Labels: status/can-merge

#13 chore: refine README.md
  README.md
Labels: status/can-merge

#14 chore: add more info
  README.md
Labels: status/can-merge

#15 config: bump ti-community-lgtm
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/config/external_plugins_config.yaml
Labels: size/XS, status/can-merge

#16 chore: refine README.md
  README.md
Labels: size/XS, status/can-merge

#17 chore: refine codecov badge
  README.md
Labels: size/XS, status/can-merge

#18 chore: refine typo
  README.md
Labels: status/can-merge

#19 feat: add approve config
  pkg/externalplugins/config.go
  pkg/externalplugins/config_test.go
Labels: status/can-merge

#23 test: fix typo
  pkg/externalplugins/config_test.go
  pkg/ownersclient/ownersclient_test.go
Labels: size/S, status/can-merge

#24 feat: rename committers to approvers
  pkg/ownersclient/ownersclient.go
  pkg/ownersclient/ownersclient_test.go
Labels: size/M, status/can-merge

#25 fix: rename approve to merge
  pkg/externalplugins/config.go
  pkg/externalplugins/config_test.go
Labels: size/XL, status/can-merge

#26 fix: rename ti community merge
  pkg/externalplugins/config.go
  pkg/externalplugins/config_test.go
Labels: status/can-merge

#27 config: add ti community merge
  configs/prow/cluster/ing_ingress.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_merge_service.yaml
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugin.yaml
Labels: size/L, status/can-merge

#31 config: remove tls
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/ing_ingress.yaml
  configs/prow/cluster/minio.yaml
Labels: size/S, status/can-merge

#32 config: replace s3 with gcs
  .gitignore
  configs/prow/Makefile
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/minio.yaml
  configs/prow/cluster/s3_secrets.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/config/config.yaml
Labels: size/L, status/can-merge

#33 config: add plank and enable pr status
  .gitignore
  configs/prow/Makefile
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/plank_rbac.yaml
  configs/prow/cluster/plank_service.yaml
  configs/prow/config/config.yaml
Labels: size/L, status/can-merge

#34 config: add config updater
  configs/prow/Makefile
  configs/prow/config/config.yaml
  configs/prow/config/plugin.yaml
  configs/prow/config/plugins.yaml
Labels: size/XL, status/can-merge

#35 config: add welcome message
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#36 config: use lifecycle
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#37 config: add updater for external config
  configs/prow/Makefile
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/can-merge

#38 config: add namespace
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#39 config: remove help
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#40 config: refine welcome
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#41 config: add new line
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#42 config: add tidb for test dev
  configs/prow/config/config.yaml
Labels: size/XS, status/can-merge

#43 config: update URL
  configs/prow/config/external_plugins_config.yaml
Labels: size/XS, status/can-merge

#44 config: add tikv community
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#45 config: refine fmt
  configs/prow/config/external_plugins_config.yaml
Labels: size/XS, status/can-merge

#46 config: add assign for tikv community
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#47 config: use https
  configs/prow/cluster/ing_ingress.yaml
  configs/prow/config/config.yaml
Labels: size/S, status/can-merge

#48 config: fix oauth url
  configs/prow/cluster/deck_deployment.yaml
Labels: size/XS, status/can-merge

#49 config: not allow http
  configs/prow/cluster/ing_ingress.yaml
Labels: size/XS, status/can-merge

#52 config: add branch for tikv community
  configs/prow/config/config.yaml
Labels: size/S, status/can-merge

#53 config: refine protect
  configs/prow/config/config.yaml
Labels: size/XS, status/can-merge

#54 config: add branch protection
  configs/prow/cluster/branchprotector.yaml
  configs/prow/config/config.yaml
Labels: size/M, status/can-merge

#55 config: bump lgtm and merge
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
Labels: status/can-merge

#56 config: add ti community owners
  configs/prow/cluster/ing_ingress.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/ti_community_owners_service.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/L, status/can-merge

#57 config: add tide for ti community owners
  configs/prow/config/config.yaml
Labels: size/XS, status/LGT2, status/can-merge

#58 config: add configs for tidb-community-bots
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/LGT2, status/can-merge

#59 config: add label sync
  configs/prow/Makefile
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/config/labels.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/LGT2, status/can-merge

#60 config: add more labels
  configs/prow/config/labels.yaml
Labels: size/M, status/LGT2, status/can-merge

#61 feat: merge plugins
  .github/workflows/golangci-lint.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  .goreleaser.yml
  Makefile
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
  configs/prow/cluster/label_sync.yaml
  configs/prow/config/config.yaml
  go.mod
  go.sum
  pkg/externalplugins/lgtm/lgtm.go
  pkg/externalplugins/lgtm/lgtm_test.go
  pkg/externalplugins/merge/merge.go
  pkg/externalplugins/merge/merge_test.go
  pkg/externalplugins/owners/owners.go
  pkg/externalplugins/owners/owners_test.go
  pkg/externalplugins/owners/types.go
Labels: size/XXL

#62 chore: add dockerfiles
  .goreleaser.yml
  deployments/plugins/lgtm/Dockerfile
  deployments/plugins/merge/Dockerfile
  deployments/plugins/owners/Dockerfile
Labels: size/S, status/can-merge

#63 fix: move it into internal
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/owners/types.go
  internal/pkg/externalplugins/plugins.go
  internal/pkg/externalplugins/plugins_test.go
  internal/pkg/externalplugins/respond.go
  internal/pkg/externalplugins/respond_test.go
  internal/pkg/ownersclient/ownersclient.go
  internal/pkg/ownersclient/ownersclient_test.go
Labels: size/M, status/can-merge

#64 feat: impl owners
  cmd/ticommunityowners/main.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/owners/types.go
  internal/pkg/ownersclient/ownersclient.go
  internal/pkg/ownersclient/types.go
Labels: size/XXL, status/can-merge

#65 config: add owners config
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
  configs/prow/Makefile
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/config/external_plugins_config.yaml
Labels: size/S, status/can-merge

#66 config: bump plugins version
  .github/workflows/test.yml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/XS, status/can-merge

#67 feat: impl label
  .goreleaser.yml
  cmd/ticommunitylabel/main.go
  deployments/plugins/label/Dockerfile
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
Labels: size/XXL, status/can-merge

#70 fix: refine label
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_label_service.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/plugins.yaml
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
Labels: size/L, status/can-merge

#71 config: bump version
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/XS, status/can-merge

#72 config: add require-matching-label for prow
  configs/prow/config/labels.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/can-merge

#74 fix: add default sig name
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/M, status/can-merge

#75 fix: use trust team
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/L, status/can-merge

#76 config: bump version
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
Labels: size/XS, status/can-merge

#78 config: add needs-rebase
  .github/workflows/rebase.yml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/needs-rebase_service.yaml
  configs/prow/config/config.yaml
  configs/prow/config/plugins.yaml
Labels: size/M, status/can-merge

#77 docs: add book
  docs/.gitignore
  docs/book.toml
  docs/src/SUMMARY.md
  docs/src/chapter_1.md
Labels: size/S, status/can-merge

#79 config: refine config
  configs/prow/config/plugins.yaml
Labels: size/XS, status/can-merge

#80 feat: remove lgtm auto remove
  cmd/ticommunitylgtm/main.go
  configs/prow/config/external_plugins_config.yaml
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/plugins_test.go
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
Labels: size/XXL, status/can-merge

#81 fix: rename pull owners url
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/config/external_plugins_config.yaml
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/plugins_test.go
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
Labels: size/L, status/can-merge

#82 config: cleanup config
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/config/config.yaml
  configs/prow/config/external_plugins_config.yaml
  configs/prow/config/labels.yaml
  configs/prow/config/plugins.yaml
Labels: size/XL, status/can-merge

#83 config: add needs-rebase config
  configs/prow/config/labels.yaml
  configs/prow/config/plugins.yaml
Labels: size/S, status/can-merge

#84 fix: add command help link
  internal/pkg/externalplugins/respond.go
Labels: size/XS, status/can-merge

#85 build: bump version
  configs/prow/cluster/branchprotector.yaml
  configs/prow/cluster/crier_deployment.yaml
  configs/prow/cluster/deck_deployment.yaml
  configs/prow/cluster/ghproxy.yaml
  configs/prow/cluster/hook_deployment.yaml
  configs/prow/cluster/horologium_deployment.yaml
  configs/prow/cluster/label_sync.yaml
  configs/prow/cluster/needs-rebase_deployment.yaml
  configs/prow/cluster/plank_deployment.yaml
  configs/prow/cluster/prow_controller_manager_deployment.yaml
  configs/prow/cluster/sinker_deployment.yaml
  configs/prow/cluster/statusreconciler_deployment.yaml
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/cluster/tide_deployment.yaml
  configs/prow/config/config.yaml
Labels: size/M, status/can-merge

#86 config: fix typo
  configs/prow/cluster/ti_community_label_deployment.yaml
  configs/prow/cluster/ti_community_lgtm_deployment.yaml
  configs/prow/cluster/ti_community_merge_deployment.yaml
  configs/prow/cluster/ti_community_owners_deployment.yaml
  configs/prow/config/external_plugins_config.yaml
Labels: size/S, status/can-merge
