Repository ti-community-infra/tichi, pull requests merged in 2020-12, with the labels that each got.

#175 docs: add tools doc
  docs/src/SUMMARY.md
  docs/src/components/tide.md
  docs/src/plugins/merge.md
  docs/src/plugins/require-matching-label.md
  docs/src/tools.md
  docs/src/tools/label_sync.md
Labels: size/L, status/LGT1, status/can-merge

#176 config: setting defalut labels
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/config/labels.yaml
Labels: size/L, status/LGT1, status/can-merge

#177 feat: label support ExcludeLabels
  docs/src/plugins/label.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
Labels: size/L, status/LGT1, status/can-merge

#179 chore: remove useless comments
  .gitignore
Labels: size/XS, status/LGT1, status/can-merge

#180 config: add exclude_labels for test-dev
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/XS, status/can-merge

#182 feat: add label-dumpling
  .gitignore
  experiment/README.md
  experiment/label-dumpling/.gitignore
  experiment/label-dumpling/Cargo.toml
  experiment/label-dumpling/src/main.rs
Labels: size/L, status/LGT1, status/can-merge

#183 chore: refine .gitattributes
  .gitattributes
Labels: size/XS, status/can-merge

#184 feat: add phony-rs
  experiment/.gitignore
  experiment/phony-rs/Cargo.toml
  experiment/phony-rs/README.md
  experiment/phony-rs/src/main.rs
  experiment/phony-rs/static/index.html
Labels: size/L, status/LGT1, status/can-merge

#185 fix: delay tars reply
  internal/pkg/externalplugins/tars/tars.go
Labels: size/S, status/LGT1, status/can-merge

#186 build: bump version
  .prow.yaml
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
Labels: size/M, status/LGT1, status/can-merge

#187 config: enable milestone for test dev
  configs/prow-dev/config/plugins.yaml
Labels: size/S, status/can-merge

#189 docs: refine lgtm
  docs/src/plugins/lgtm.md
Labels: size/S, status/LGT1, status/can-merge

#190 refactor: move the label and label preifx constants to label.go
  internal/pkg/externalplugins/label.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners.go
Labels: size/L, status/LGT1, status/can-merge

#192 build: deploy cherrypicker
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/cluster/cherrypicker_service.yaml
Labels: size/M, status/LGT1, status/can-merge

#193 config: enable cherrypick for test dev
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/config/plugins.yaml
Labels: do-not-merge/hold, size/XS

#196 config: refine cherrypicker name
  configs/prow-dev/cluster/cherrypicker_service.yaml
  configs/prow-dev/config/plugins.yaml
Labels: size/XS, status/LGT1, status/can-merge

#197 chore: remove label workflow
  docs/src/SUMMARY.md
  docs/src/workflows/label.md
Labels: size/XS, status/LGT1, status/can-merge

#198 docs: add hold and wip
  docs/src/SUMMARY.md
  docs/src/plugins/hold.md
  docs/src/plugins/wip.md
Labels: size/M, status/LGT1, status/can-merge

#199 refactor: update default path of the external plugin config file
  cmd/ticommunityautoresponder/main.go
  cmd/ticommunityblunderbuss/main.go
  cmd/ticommunitylabel/main.go
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
Labels: size/S, status/LGT1, status/can-merge

#200 config: enable trigger for test dev
  configs/prow-dev/config/plugins.yaml
Labels: size/XS, status/can-merge

#202 refactor: update the mount path of external plugins config
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge

#201 feat: add rerere component
  .goreleaser.yml
  cmd/rerere/main.go
  deployments/components/rerere/Dockerfile
  go.mod
  go.sum
  internal/pkg/externalplugins/autoresponder/autoresponder_test.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/tars/tars_test.go
  internal/pkg/ownersclient/ownersclient_test.go
  internal/pkg/rerere/rerere.go
  internal/pkg/rerere/rerere_test.go
Labels: size/XXL, status/LGT1, status/can-merge

#203 build: bump version
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: size/S, status/can-merge

#204 ci: add rerere
  .github/workflows/golangci-lint.yml
  .github/workflows/test.yml
  .prow.yaml
  internal/pkg/rerere/rerere.go
Labels: size/S, status/can-merge

#207 chore: ignore unused parameter
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
Labels: size/XS, status/can-merge

#208 fix: refine rerere flags
  cmd/rerere/main.go
  internal/pkg/rerere/rerere.go
Labels: size/M, status/can-merge

#209 ci: add trigger for rerere
  .prow.yaml
Labels: size/XS, status/can-merge

#210 feat: support setting multiple trusted teams and required LGTM for branches
  docs/src/plugins/owners.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/L, status/LGT1, status/can-merge

#194 refactor: improve the response sentences
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/labels.yaml
  configs/prow-dev/config/plugins.yaml
  docs/src/plugins/lgtm.md
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/tars/tars.go
Labels: ok-to-test, size/L, status/LGT1, status/can-merge

#215 build: bump version
  .prow.yaml
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
Labels: size/M, status/can-merge

#216 chore: rename org
  Makefile
  README.md
  cmd/rerere/main.go
  cmd/ticommunityautoresponder/main.go
  cmd/ticommunityblunderbuss/main.go
  cmd/ticommunitylabel/main.go
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
  cmd/ticommunitytars/main.go
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/labels.yaml
  configs/prow-dev/config/plugins.yaml
  docs/src/introduction.md
  docs/src/plugins/blunderbuss.md
  docs/src/plugins/label.md
  docs/src/plugins/lgtm.md
  docs/src/plugins/merge.md
  docs/src/plugins/owners.md
  docs/src/plugins/require-matching-label.md
  docs/src/plugins/tars.md
  docs/src/plugins/wip.md
  docs/src/tools/label_sync.md
  go.mod
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/autoresponder/autoresponder_test.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/plugins_test.go
  internal/pkg/externalplugins/respond.go
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
  internal/pkg/ownersclient/ownersclient_test.go
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
Labels: size/XL, status/can-merge

#217 feat: add delay time for bluderbuss to wait for sig label to be added
  docs/src/plugins/blunderbuss.md
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
Labels: size/M, status/LGT1, status/can-merge

#219 config: add rustin-bot-periodics.yaml
  .prow.yaml
  configs/prow-dev/.gitignore
  configs/prow-dev/Makefile
  configs/prow-dev/config/plugins.yaml
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
Labels: do-not-merge/hold, size/L

#220 config: add jobs
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
Labels: size/M

#221 config: fix typo
  configs/prow-dev/config/plugins.yaml
Labels: status/can-merge

#222 config: rustin bot only for test dev
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
Labels: size/S, status/can-merge

#223 config: fix rustin bot token path
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
Labels: size/XS, status/can-merge

#218 feat: auto responder support all comment events
  cmd/ticommunityautoresponder/main.go
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/autoresponder/autoresponder_test.go
Labels: size/XXL, status/LGT1, status/can-merge

#224 build: bump ti plugins verstion from v0.16.4 to v0.16.5
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S

#191 feat: add Owner page
  .github/workflows/web.yml
  web/README.md
  web/package.json
  web/pages/[org]/[repo]/pulls/[num]/owners.module.scss
  web/pages/[org]/[repo]/pulls/[num]/owners.tsx
  web/pages/api/hello.js
  web/pages/index.tsx
  web/tsconfig.json
  web/types/owners.ts
  web/utils/constant.ts
  web/utils/request.ts
Labels: size/L, status/LGT1, status/can-merge

#225 config: add more configuration items for test-dev
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
  docs/src/plugins/owners.md
Labels: size/S, status/LGT1, status/can-merge

#227 chore: bump the test-infra version
  cmd/ticommunitytars/main.go
  go.mod
  go.sum
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/M, status/LGT1, status/can-merge

#228 feat: blunderbuss supports re-cc to reviewers when sig label added
  docs/src/plugins/blunderbuss.md
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
Labels: size/XL, status/LGT1, status/can-merge

#232 fix: add waiting time for rerere
  cmd/rerere/main.go
  configs/prow-dev/config/config.yaml
  internal/pkg/externalplugins/merge/merge.go
Labels: size/M, status/LGT1, status/can-merge

#234 build: bump ti plugins verstion from v0.16.5 to v0.16.6
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge

#235 config: add sig configuration items for testing blunderbuss on test-dev
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#236 config: fix the default sig name option
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#237 docs: add rerere component
  docs/src/SUMMARY.md
  docs/src/components/rerere.md
  docs/src/workflows/pr.md
Labels: size/L

#238 fix: make the rerere quick failed
  internal/pkg/rerere/rerere.go
  internal/pkg/rerere/rerere_test.go
Labels: size/L, status/LGT1, status/can-merge

#239 refactor: refine scopelint
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/label/label_test.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/tars/tars_test.go
  internal/pkg/ownersclient/ownersclient_test.go
Labels: size/XL, status/LGT1, status/can-merge

#240 build: bump ti plugins version from v0.16.6 to v0.16.7
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge

#241 fix: remove the lgtm approve comment limit
  docs/src/plugins/lgtm.md
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
Labels: size/S, status/LGT1, status/can-merge
