Repository ti-community-infra/tichi, pull requests merged in 2021-07, with the labels that each got.

#622 config(test-dev): stop block LGT labels
  configs/prow-dev/config/external_plugins_config.yaml
Labels: dco-signoff: yes, size/XS, status/LGT1, status/can-merge

#624 ci: enable rerere for tichi
  .github/workflows/golangci-lint.yml
  .prow.yaml
Labels: dco-signoff: yes, size/M, status/LGT1, status/can-merge

#625 fix(rerere): Check every minute
  internal/pkg/rerere/rerere.go
Labels: dco-signoff: yes, size/XS, status/LGT1, status/can-merge

#626 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#632 feat: support generate labels.md
  .prow.yaml
  configs/prow-dev/.gitignore
  configs/prow-dev/config/labels.md
  configs/prow-dev/config/labels.md.tmpl
  scripts/update-labels.sh
  scripts/verify-labels.sh
Labels: dco-signoff: yes, size/L, status/LGT1, status/can-merge

#630 build: Bump golangci-lint from 1.31.0 to 1.41.1
  .github/workflows/golangci-lint.yml
  .golangci.yml
  Makefile
  cmd/check-external-plugin-config/main.go
  internal/pkg/externalplugins/config.go
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#631 feat: remove request review feature from cherrypicker
  docs/en/plugins/cherrypicker.md
  docs/plugins/cherrypicker.md
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
  internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
Labels: dco-signoff: yes, size/L, status/LGT1, status/can-merge

#637 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#639 config: remove blunderbuss config for test
  configs/prow-dev/config/external_plugins_config.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#641 build: bump all plugins version to v1.7.0
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#647 fix: fix the commenter query format
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#652 feat: add label in case of conflict
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
  internal/pkg/externalplugins/label.go
Labels: dco-signoff: yes, size/XS, status/LGT1, status/can-merge

#653 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#654 fix: Revert "feat: add label in case of conflict (#652)"
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
  internal/pkg/externalplugins/label.go
Labels: dco-signoff: yes, size/XS, status/LGT1, status/can-merge

#649 feat: return review notification by update comment
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
Labels: dco-signoff: yes, size/XL, status/LGT1, status/can-merge

#656 build: bump all ti plugins version to v1.7.1-beta.2
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge

#662 build: bump all ti plugins version to v1.7.1
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, size/S, status/LGT1, status/can-merge
