Repository ti-community-infra/tichi, pull requests merged in 2021-02, with the labels that each got.

#312 fix: fix the escape char
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/XS, status/LGT1, status/can-merge

#314 feat: support issue event and add reply for label blocker
  cmd/ticommunitylabelblocker/main.go
  docs/plugins/label-blocker.md
  go.mod
  go.sum
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/labelblocker/labelblocker.go
  internal/pkg/externalplugins/labelblocker/labelblocker_test.go
Labels: size/XL, status/LGT1, status/can-merge

#319 build: bump plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#320 config: add message to label blocker
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/XS

#321 config: fix trusted bot name
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/XS

#324 ci: cleanup label_sync.yaml and make it be a prow job
  .prow.yaml
  configs/prow-dev/cluster/label_sync.yaml
Labels: size/M, status/LGT1, status/can-merge

#333 feat: add use GitHub permission to owners
  docs/plugins/owners.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/L

#335 build: update release jobs
  .github/workflows/release.yml
  .goreleaser.yml
Labels: size/M

#336 chore: update images
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  docs/components/rerere.md
Labels: size/S

#337 build: bump test-infra components version
  .prow.yaml
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
Labels: size/M

#338 chore: bump test-infra version
  go.mod
  go.sum
Labels: size/S, status/LGT1, status/can-merge

#342 fix: Use github permissions only if no sig labels
  docs/plugins/owners.md
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/M, status/LGT1, status/can-merge

#343 build: bump ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#344 fix: only request reviewers when PR no requested reviewers
  docs/plugins/blunderbuss.md
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
Labels: size/L, status/LGT1, status/can-merge

#347 feat: add external plugin config checker
  .goreleaser.yml
  cmd/check-external-plugin-config/main.go
  cmd/check-external-plugin-config/main_test.go
  deployments/util/check-external-plugin-config/Dockerfile
  test/testdata/config_combine.yaml
Labels: size/L, status/LGT1, status/can-merge

#348 fix: fix dockerfile path in goreleaser config
  .goreleaser.yml
  deployments/utils/check-external-plugin-config/Dockerfile
Labels: size/XS, status/LGT1, status/can-merge

#349 build: bump ti plugins version and enable validate config job
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/M, status/LGT1, status/can-merge

#353 build: bump the test-infra and plugins version
  .prow.yaml
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
  go.mod
  go.sum
Labels: size/M, status/LGT1, status/can-merge

#354 style: Polish message
  configs/prow-dev/config/external_plugins_config.yaml
  docs/plugins/tars.md
  test/testdata/config_combine.yaml
Labels: ok-to-test, size/XS, status/LGT1, status/can-merge

#355 chore: remove TODO
  internal/pkg/externalplugins/config.go
Labels: size/XS, status/LGT1, status/can-merge

#359 ci: add pull-tichi-unit-test
  .github/workflows/test.yml
  .prow.yaml
  Makefile
Labels: size/M, status/LGT1, status/can-merge

#361 refactor: refine Makefile
  Makefile
Labels: size/S, status/LGT1, status/can-merge

#362 feat: blunderbuss support weighted assign
  docs/en/_sidebar.md
  docs/en/plugins/blunderbuss.md
  docs/plugins/blunderbuss.md
  go.mod
  go.sum
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
Labels: size/XL, status/LGT1, status/can-merge

#364 build: bump tichi plugins version form v1.3.0 to v1.3.1
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge
