Repository ti-community-infra/tichi, pull requests merged in 2021-03, with the labels that each got.

#366 feat: TARS supports responding to push events
  cmd/ticommunitytars/main.go
  docs/en/_sidebar.md
  docs/en/plugins/tars.md
  docs/plugins/tars.md
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/XL, status/LGT1, status/can-merge

#367 fix: merge if the number of lgtm is greater than the required number
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: size/S, status/LGT1, status/can-merge

#369 build: bump all tichi plugins versions
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge

#370 chore: limit coverage drops
  .codecov.yml
Labels: size/XS, status/LGT1, status/can-merge

#371 fix: refine tars query
  configs/prow-dev/config/plugins.yaml
  internal/pkg/externalplugins/tars/tars.go
Labels: size/XS, status/LGT1, status/can-merge

#372 build: bump all tichi plugins versions
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#368 feat: add event type enum
  cmd/ticommunityautoresponder/main.go
  cmd/ticommunityblunderbuss/main.go
  cmd/ticommunitylabel/main.go
  cmd/ticommunitylabelblocker/main.go
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunitytars/main.go
  internal/pkg/externalplugins/event_type.go
Labels: ok-to-test, size/M, status/LGT1, status/can-merge

#375 fix: check PR mergeable for tars
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/L, status/LGT1, status/can-merge

#376 fix: refine tars err check
  internal/pkg/externalplugins/tars/tars.go
Labels: size/S, status/LGT1, status/can-merge

#378 build: bump all tichi plugins versions
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#379 fix: tars wait a few seconds to give github a chance to calculate PR mergeable status
  internal/pkg/externalplugins/tars/tars.go
Labels: size/XS

#380 build: bump all tichi plugins versions
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#381 fix: refine tars sleep
  internal/pkg/externalplugins/tars/tars.go
Labels: size/S

#382 fix: tars wait more time
  internal/pkg/externalplugins/tars/tars.go
Labels: size/XS

#383 fix: Tars no longer checks mergeable
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: size/L, status/LGT1, status/can-merge

#365 feat: support log level config for external plugin
  cmd/ticommunityautoresponder/main.go
  cmd/ticommunityblunderbuss/main.go
  cmd/ticommunitylabel/main.go
  cmd/ticommunitylabelblocker/main.go
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
  cmd/ticommunitytars/main.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/plugins.go
  test/testdata/config_combine.yaml
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
Labels: size/L, status/LGT1, status/can-merge

#384 build: bump all tichi plugins version to v1.3.6
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/S, status/LGT1, status/can-merge

#386 fix: adjust TARS scan period to one hour
  cmd/ticommunitytars/main.go
  docs/en/plugins/tars.md
  docs/plugins/tars.md
Labels: size/XS, status/LGT1, status/can-merge

#387 refactor: improve label help messages
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
Labels: size/S, status/LGT1, status/can-merge

#389 build: bump all tichi plugins versions
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge

#388 chore: refine codecov
  .prow.yaml
  Makefile
Labels: size/S, status/LGT1, status/can-merge

#404 refactor: add help provider type
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/labelblocker/labelblocker.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/tars/tars.go
Labels: ok-to-test, size/L, status/LGT1, status/can-merge

#406 docs: add translation for lgtm
  docs/en/_sidebar.md
  docs/en/plugins/lgtm.md
  docs/plugins/lgtm.md
Labels: size/L, status/LGT1, status/can-merge

#410 docs: add translation for owners
  docs/en/_sidebar.md
  docs/en/plugins/owners.md
  docs/plugins/owners.md
Labels: size/L, status/LGT1, status/can-merge

#413 docs: add translations to the k8s plugins
  docs/en/_sidebar.md
  docs/en/plugins/hold.md
  docs/en/plugins/require-matching-label.md
  docs/en/plugins/wip.md
  docs/plugins/hold.md
  docs/plugins/require-matching-label.md
  docs/plugins/wip.md
Labels: size/L, status/LGT1, status/can-merge

#412 docs: add translation for label and label-blocker
  docs/en/_sidebar.md
  docs/en/plugins/label-blocker.md
  docs/en/plugins/label.md
  docs/plugins/label-blocker.md
  docs/plugins/label.md
Labels: size/L, status/LGT1, status/can-merge

#417 docs: add tichi plugin summary
  docs/README.md
  docs/en/README.md
Labels: size/M, status/LGT1, status/can-merge

#418 docs: clenup rerere and add translation for tools and components
  .github/workflows/golangci-lint.yml
  .goreleaser.yml
  cmd/rerere/main.go
  deployments/components/.gitkeep
  deployments/components/rerere/Dockerfile
  docs/README.md
  docs/_sidebar.md
  docs/components/rerere.md
  docs/components/tide.md
  docs/en/README.md
  docs/en/_sidebar.md
  docs/en/components.md
  docs/en/components/tide.md
  docs/en/tools/label_sync.md
  docs/en/workflows/pr.md
  docs/tools/label_sync.md
  docs/workflows/pr.md
  internal/pkg/rerere/rerere.go
  internal/pkg/rerere/rerere_test.go
Labels: size/XXL, status/LGT1, status/can-merge

#421 build: bump test-infra version
  .prow.yaml
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
  go.mod
  go.sum
Labels: size/M, status/LGT1, status/can-merge

#416 fix: fix the /label command case sensitive problem and optimize reply
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
Labels: size/XXL, status/LGT1, status/can-merge

#422 build: bump ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S, status/LGT1, status/can-merge

#424 config: add label config for test-dev
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/S, status/LGT1, status/can-merge

#425 feat: impl contribution
  .goreleaser.yml
  cmd/ticommunitycontribution/main.go
  deployments/plugins/contribution/Dockerfile
  docs/README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/_sidebar.md
  docs/en/plugins/contribution.md
  docs/plugins/contribution.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/contribution/contribution.go
  internal/pkg/externalplugins/contribution/contribution_test.go
  internal/pkg/externalplugins/label.go
  internal/pkg/externalplugins/label/label_test.go
Labels: size/XXL, status/LGT1, status/can-merge

#430 config: enable contribution for test-dev
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: size/XS

#431 fix: add better log and more associations for contribution
  internal/pkg/externalplugins/contribution/contribution.go
  internal/pkg/externalplugins/contribution/contribution_test.go
Labels: size/S, status/LGT1, status/can-merge

#432 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#436 chore: add bump to semantic types
  .github/semantic.yml
Labels: size/XS, status/LGT1, status/can-merge

#439 refactor: FormatTestLabels support more args
  internal/pkg/externalplugins/contribution/contribution_test.go
  internal/pkg/externalplugins/label.go
  internal/pkg/externalplugins/label/label_test.go
  internal/pkg/externalplugins/label_test.go
Labels: size/L, status/LGT1, status/can-merge

#445 ci: move tichi web CI to prow job
  .github/workflows/web.yml
  .prow.yaml
Labels: size/M, status/LGT1, status/can-merge

#449 docs: add autobump tool doc
  README.md
  docs/README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/_sidebar.md
  docs/en/tools/autobump.md
  docs/tools/autobump.md
Labels: size/L, status/LGT1, status/can-merge
