Repository ti-community-infra/tichi, pull requests merged in 2021-04, with the labels that each got.

#451 feat: impl cherrypicker
  .codecov.yml
  .goreleaser.yml
  cmd/ticommunitycherrypicker/main.go
  deployments/plugins/cherrypicker/Dockerfile
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
  internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  test/testdata/lgtm_comment.json
  test/testdata/opened_pr.json
Labels: size/XXL, status/LGT1, status/can-merge

#462 ci: fix cherrypicker missing git issue
  deployments/plugins/cherrypicker/Dockerfile
Labels: size/XS

#463 build: bump all plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#466 docs: add prow plugins document
  docs/README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/_sidebar.md
  docs/en/plugins/assign.md
  docs/en/plugins/milestone.md
  docs/en/plugins/needs-rebase.md
  docs/en/plugins/size.md
  docs/plugins/assign.md
  docs/plugins/milestone.md
  docs/plugins/needs-rebase.md
  docs/plugins/size.md
Labels: contribution, first-time-contributor, ok-to-test, size/XL, status/LGT1, status/can-merge

#468 ci: add corn job to sync labels
  .prow.yaml
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/config/labels.yaml
Labels: dco-signoff: yes, release-note-none, size/M

#471 config: make tide required for test-dev
  configs/prow-dev/config/config.yaml
Labels: dco-signoff: yes, release-note-none, size/XS

#472 chore: remove unused prettier ignore
  web/.prettierignore
Labels: dco-signoff: yes, release-note-none, size/XS, status/LGT1, status/can-merge

#473 chore: remove unused semantic
  .github/semantic.yml
Labels: dco-signoff: yes, release-note-none, size/XS, status/LGT1, status/can-merge

#474 fix: Use MergeStateStatus to reduce the use of tars for the GitHub API
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: dco-signoff: yes, release-note, size/M, status/LGT1, status/can-merge

#475 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#477 fix: Revert "fix: Use MergeStateStatus to reduce the use of tars for the GitHub API(#474)"
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: dco-signoff: yes, release-note-none, size/M, status/LGT1, status/can-merge

#480 fix: tars stop handle pull request event and more refined queries
  cmd/ticommunitytars/main.go
  go.sum
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: dco-signoff: yes, release-note, size/XL, status/LGT1, status/can-merge

#481 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#482 docs: add release-note docs
  docs/README.md
  docs/_sidebar.md
  docs/en/README.md
  docs/en/_sidebar.md
  docs/en/plugins/release-note.md
  docs/plugins/release-note.md
Labels: dco-signoff: yes, release-note-none, size/L, status/LGT1, status/can-merge

#484 clarify the logic of contribution label
  docs/en/plugins/contribution.md
  docs/plugins/contribution.md
Labels: contribution, dco-signoff: yes, first-time-contributor, ok-to-test, release-note-none, size/S, status/LGT1, status/can-merge

#483 fix: Make tars periodically update only one PR to prevent DOS attacks to CI systems
  cmd/ticommunitytars/main.go
  docs/en/plugins/tars.md
  docs/plugins/tars.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/tars/tars.go
Labels: dco-signoff: yes, release-note, size/L, status/LGT1, status/can-merge

#485 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#489 fix: lgtm start responding to review comment
  docs/en/plugins/lgtm.md
  docs/plugins/lgtm.md
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
Labels: dco-signoff: yes, release-note, size/M, status/LGT1, status/can-merge

#490 build: support auto https redirect
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/ing_ingress.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, release-note-none, size/M, status/LGT1, status/can-merge

#491 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#492 fix: try to create all picks and return aggregate error
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
Labels: dco-signoff: yes, release-note, size/XS, status/LGT1, status/can-merge

#493 feat: support multiple calls per comment
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
  internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
Labels: dco-signoff: yes, release-note, size/M, status/LGT1, status/can-merge

#494 feat: cherrypicker supports pushing conflicts directly
  go.mod
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
Labels: dco-signoff: yes, release-note, size/M, status/LGT1, status/can-merge

#497 fix: refine conflicts of `git am`
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#498 feat: cherrypicker support auto-add picked label
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
  internal/pkg/externalplugins/cherrypicker/cherrypicker_test.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/label.go
Labels: dco-signoff: yes, release-note, size/L, status/LGT1, status/can-merge

#502 fix: refine git am automatically aborted
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#503 fix: refine git am failed issue
  internal/pkg/externalplugins/cherrypicker/cherrypicker.go
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#504 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  configs/prow-dev/config/external_plugins_config.yaml
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge

#508 fix: use git 2.30.2 for cherrypicker
  deployments/plugins/cherrypicker/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/XS, status/LGT1, status/can-merge

#509 fix: refine dockerfile typo
  deployments/plugins/cherrypicker/Dockerfile
Labels: dco-signoff: yes, release-note-none, size/XS, status/LGT1, status/can-merge

#511 build: bump all ti plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti-community-cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: dco-signoff: yes, release-note-none, size/S, status/LGT1, status/can-merge
