Repository ti-community-infra/tichi, pull requests merged in 2021-01, with the labels that each got.

#233 feat: add link
  .github/workflows/web.yml
  web/.gitignore
  web/README.md
  web/components/header/index.tsx
  web/next-env.d.ts
  web/next.config.js
  web/package.json
  web/pages/[org]/[repo]/pulls/[num]/owners.module.scss
  web/pages/[org]/[repo]/pulls/[num]/owners.tsx
  web/pages/_app.tsx
  web/pages/index.tsx
  web/public/favicon.ico
  web/public/vercel.svg
  web/styles/globals.css
  web/styles/home.module.scss
  web/tsconfig.json
  web/types/owners.ts
  web/utils/constant.ts
  web/utils/request.ts
Labels: do-not-merge/hold, size/XL

#242 chore: add slack and book link to README.md
  README.md
Labels: size/S, status/LGT1, status/can-merge

#244 chore: migrate mdbook to docsify
  .github/workflows/gh-pages.yml
  .github/workflows/preview.yml
  docs/.gitignore
  docs/.nojekyll
  docs/README.md
  docs/book.toml
  docs/components.md
  docs/components/rerere.md
  docs/components/tide.md
  docs/drawios/pr-workflow.drawio
  docs/index.html
  docs/plugins.md
  docs/plugins/blunderbuss.md
  docs/plugins/hold.md
  docs/plugins/label.md
  docs/plugins/lgtm.md
  docs/plugins/merge.md
  docs/plugins/owners.md
  docs/plugins/require-matching-label.md
  docs/plugins/tars.md
  docs/plugins/wip.md
  docs/src/SUMMARY.md
  docs/summary.md
  docs/tools.md
  docs/tools/label_sync.md
  docs/workflows.md
  docs/workflows/pr.md
Labels: do-not-merge/hold, size/L, status/LGT1

#245 docs: add nav bar
  docs/_navbar.md
  docs/_sidebar.md
  docs/index.html
Labels: size/XS, status/LGT1, status/can-merge

#250 docs: add merge translation
  docs/en/_sidebar.md
  docs/en/plugins.md
  docs/en/plugins/merge.md
  docs/plugins.md
  docs/plugins/merge.md
Labels: size/L, status/LGT1, status/can-merge

#249 feat: support multiple sigs for owners
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
Labels: size/XL, status/LGT1, status/can-merge

#251 refactor: improve can not merge message
  internal/pkg/externalplugins/merge/merge.go
Labels: size/XS, status/LGT1, status/can-merge

#252 build: bump plugins version
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S

#246 feat: add chingwei
  cmd/chingwei/main.go
  deployments/components/chingwei/Dockerfile
  experiment/chingwei/chingwei.go
Labels: size/L

#256 config: add merge_commit_template
  configs/prow-dev/config/config.yaml
Labels: size/XS

#254 refactor: rename some variables
  .github/workflows/web.yml
  web/components/header/index.tsx
  web/package.json
  web/pages/[org]/[repo]/pulls/[num]/owners.module.scss
  web/pages/[org]/[repo]/pulls/[num]/owners.tsx
  web/pages/_app.tsx
  web/pages/index.tsx
  web/styles/home.module.scss
  web/types/constant.ts
  web/utils/request.ts
Labels: size/L, status/LGT1, status/can-merge

#259 feat: giving permissions to all sig reviewers and committers
  docs/plugins/owners.md
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/owners/types.go
Labels: size/XL, status/LGT1, status/can-merge

#262 build: bump plugins verison from v0.17.0 to v0.17.1
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S

#263 chore: rename bot
  configs/prow-dev/config/external_plugins_config.yaml
  docs/en/workflows/pr.md
  docs/plugins/blunderbuss.md
  docs/workflows/pr.md
Labels: size/S, status/LGT1, status/can-merge

#265 chore: rename project
  .goreleaser.yml
  .prow.yaml
  Makefile
  README.md
  cmd/rerere/main.go
  cmd/ticommunityautoresponder/main.go
  cmd/ticommunityblunderbuss/main.go
  cmd/ticommunitylabel/main.go
  cmd/ticommunitylgtm/main.go
  cmd/ticommunitymerge/main.go
  cmd/ticommunityowners/main.go
  cmd/ticommunitytars/main.go
  configs/prow-dev/config/plugins.yaml
  docs/README.md
  docs/components/rerere.md
  docs/en/README.md
  docs/en/plugins/merge.md
  docs/index.html
  docs/plugins/blunderbuss.md
  docs/plugins/label.md
  docs/plugins/lgtm.md
  docs/plugins/merge.md
  docs/plugins/owners.md
  docs/plugins/require-matching-label.md
  docs/plugins/tars.md
  docs/plugins/wip.md
  go.mod
  internal/pkg/externalplugins/autoresponder/autoresponder.go
  internal/pkg/externalplugins/autoresponder/autoresponder_test.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss.go
  internal/pkg/externalplugins/blunderbuss/blunderbuss_test.go
  internal/pkg/externalplugins/label/label.go
  internal/pkg/externalplugins/label/label_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
  internal/pkg/externalplugins/owners/owners.go
  internal/pkg/externalplugins/owners/owners_test.go
  internal/pkg/externalplugins/respond.go
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: do-not-merge/hold, size/L

#266 build: bump plugins version
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
Labels: size/S

#267 refactor: rewrite owners page
  .goreleaser.yml
  deployments/web/Dockerfile
  web/.gitignore
  web/.prettierignore
  web/components/.keep
  web/components/header/index.tsx
  web/next-env.d.ts
  web/next.config.js
  web/package-lock.json
  web/package.json
  web/pages/[org]/[repo]/pulls/[num]/owners.module.scss
  web/pages/[org]/[repo]/pulls/[num]/owners.tsx
  web/pages/index.tsx
  web/styles/home.module.scss
  web/types/constant.ts
  web/types/owners.ts
  web/utils/request.ts
Labels: size/XXL, status/LGT1, status/can-merge

#268 chore: fix releaser typo
  .goreleaser.yml
Labels: size/XS

#269 config: fix web Dockerfile env issue
  deployments/web/Dockerfile
Labels: size/XS

#270 fix: add base path for tichi-web
  web/next.config.js
Labels: size/XS

#271 config: add tichi-web deployment files
  .prow.yaml
  configs/prow-dev/cluster/ing_ingress.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  configs/prow-dev/cluster/tichi_web_service.yaml
Labels: size/M, status/LGT1, status/can-merge

#273 feat: add glue code to chingwei
  deployments/components/chingwei/Dockerfile
  experiment/chingwei/chingwei.go
  experiment/chingwei/mysql.go
  experiment/chingwei/parse.go
  experiment/chingwei/tidb.go
Labels: ok-to-test, size/M

#274 fix glue code for compilation
  experiment/chingwei/chingwei.go
  experiment/chingwei/mysql.go
  experiment/chingwei/parse.go
  experiment/chingwei/tidb.go
  go.mod
  go.sum
Labels: ok-to-test, size/L

#275 implement PrepareTiDB and Reproduce
  deployments/components/chingwei/Dockerfile
  experiment/chingwei/chingwei.go
  experiment/chingwei/mysql.go
  experiment/chingwei/parse.go
  experiment/chingwei/tidb.go
  wait-for-it.sh
Labels: ok-to-test, size/XL

#277 feat: create github comment
  experiment/chingwei/chingwei.go
  experiment/chingwei/mysql.go
  experiment/chingwei/parse.go
  experiment/chingwei/parser.go
  experiment/chingwei/tidb.go
  experiment/chingwei/types.go
  go.mod
  go.sum
Labels: size/XL

#278 feat: add github comment diff template
  experiment/chingwei/chingwei.go
Labels: needs-ok-to-test, size/S

#279 feat: add label
  experiment/chingwei/chingwei.go
  go.mod
  go.sum
Labels: size/M

#281 chore: update README.md
  README.md
Labels: size/XS

#280 feat: support find owners endpoint
  web/.gitignore
  web/.prettierignore
  web/package-lock.json
  web/package.json
  web/pages/[org]/[repo]/pulls/[num]/owners.tsx
  web/types/constant.ts
Labels: size/M, status/LGT1, status/can-merge

#283 feat: use tichi owners page
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/merge/merge.go
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
  web/pages/[org]/[repo]/pulls/[num]/owners.tsx
Labels: size/L, status/LGT1, status/can-merge

#284 config: bump the plugins version from v0.17.3 to v0.17.4
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  configs/prow-dev/config/config.yaml
Labels: size/M

#286 config: bump version from v0.17.4 to v0.17.5
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: do-not-merge/hold, size/S

#287 config: refine timeout
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/XS

#290 fix: remove merge limit for committer
  docs/en/plugins/merge.md
  docs/plugins/merge.md
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: size/M, status/LGT1, status/can-merge

#289 feat: add review notification
  cmd/ticommunitylgtm/main.go
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
  test/testdata/config_test.yaml
  test/testdata/config_update.yaml
Labels: size/XXL, status/LGT1, status/can-merge

#293 build: bump version to v1.0.0
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
  configs/prow-dev/config/external_plugins_config.yaml
Labels: size/S

#294 fix: refine lgtm delete comments issue
  internal/pkg/externalplugins/lgtm/lgtm.go
  internal/pkg/externalplugins/lgtm/lgtm_test.go
Labels: size/L, status/LGT1, status/can-merge

#295 build: bump version to v1.0.1
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: size/S

#297 chore: fix typo
  internal/pkg/externalplugins/lgtm/lgtm.go
Labels: size/S

#298 config: send pull request event to lgtm
  configs/prow-dev/config/plugins.yaml
Labels: size/XS

#299 chore: add comments for makefile
  configs/prow-dev/Makefile
  configs/prow-dev/cluster/gcs-secrets.example.yaml
  configs/prow-dev/cluster/github-token.example.yaml
  configs/prow-dev/cluster/hmac-token.example.yaml
Labels: size/M, status/LGT1, status/can-merge

#296 feat: async support for phony-rs
  experiment/phony-rs/Cargo.toml
  experiment/phony-rs/src/main.rs
  experiment/phony-rs/static/index.html
Labels: ok-to-test, size/L, status/LGT1, status/can-merge

#300 fix: update dependencies to remove panic
  experiment/label-dumpling/Cargo.toml
  experiment/label-dumpling/src/main.rs
Labels: ok-to-test, size/XS, status/LGT1, status/can-merge

#303 build: bump test-infra deps version
  .prow.yaml
  configs/prow-dev/cluster/branchprotector.yaml
  configs/prow-dev/cluster/cherrypicker_deployment.yaml
  configs/prow-dev/cluster/crier_deployment.yaml
  configs/prow-dev/cluster/deck_deployment.yaml
  configs/prow-dev/cluster/ghproxy.yaml
  configs/prow-dev/cluster/hook_deployment.yaml
  configs/prow-dev/cluster/horologium_deployment.yaml
  configs/prow-dev/cluster/label_sync.yaml
  configs/prow-dev/cluster/needs-rebase_deployment.yaml
  configs/prow-dev/cluster/plank_deployment.yaml
  configs/prow-dev/cluster/prow_controller_manager_deployment.yaml
  configs/prow-dev/cluster/sinker_deployment.yaml
  configs/prow-dev/cluster/statusreconciler_deployment.yaml
  configs/prow-dev/cluster/tide_deployment.yaml
  configs/prow-dev/config/config.yaml
  configs/prow-dev/jobs/ti-community-infra/test-dev/rustin-bot-periodics.yaml
  go.mod
  go.sum
Labels: size/L

#305 config: add tars for test-dev repo
  configs/prow-dev/config/config.yaml
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#304 feat: add label blocker plugin
  cmd/ticommunitylabelblocker/main.go
  docs/_sidebar.md
  docs/plugins/label-blocker.md
  docs/plugins/label.md
  internal/pkg/externalplugins/config.go
  internal/pkg/externalplugins/config_test.go
  internal/pkg/externalplugins/labelblocker/labelblocker.go
  internal/pkg/externalplugins/labelblocker/labelblocker_test.go
Labels: size/XXL, status/LGT1, status/can-merge

#308 config: add Dockerfile and releaser config for label blocker
  .goreleaser.yml
  deployments/plugins/labelblocker/Dockerfile
Labels: size/S, status/LGT1, status/can-merge

#310 config: add label-blocker for test-dev repo
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: size/S, status/LGT1, status/can-merge

#311 config: move the example yaml files into examples
  configs/prow-dev/examples/gcs-secrets.example.yaml
  configs/prow-dev/examples/github-token.example.yaml
  configs/prow-dev/examples/hmac-token.example.yaml
Labels: size/XS, status/LGT1, status/can-merge
