Repository ti-community-infra/tichi, pull requests merged in 2021-09, with the labels that each got.

#714 config: test blockades for ti-community-infra/test-dev
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: status/can-merge, size/S, status/LGT1, dco-signoff: yes

#715 fix: trust mini-bot for label-blocker
  configs/prow-dev/config/external_plugins_config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#719 fix(merge): If the commit hash is not found, check each commit
  internal/pkg/externalplugins/merge/merge.go
  internal/pkg/externalplugins/merge/merge_test.go
Labels: status/can-merge, size/S, status/LGT1, ok-to-test, contribution, dco-signoff: yes

#720 fix: fix tars redundant merge base operation problem
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: status/can-merge, size/L, status/LGT1, dco-signoff: yes

#722 config: make dependabot do update weekly
  .github/dependabot.yml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#723 build: bump ti plugin version from v1.8.1 to v1.8.2-beta.1
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: status/can-merge, size/S, status/LGT1, dco-signoff: yes

#724 config: enable tars for test-dev
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: status/can-merge, size/S, status/LGT1, dco-signoff: yes

#725 fix: require PR up-to-date for test-dev
  configs/prow-dev/config/config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#726 build: bump ti plugins version from v1.8.2-beta.1 to v1.8.2
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: status/can-merge, size/S, status/LGT1, dco-signoff: yes

#727 fix(tars): reduce graphql API call
  internal/pkg/externalplugins/tars/tars.go
  internal/pkg/externalplugins/tars/tars_test.go
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#728 build: bump gin version to v1.7.0
  go.mod
  go.sum
Labels: status/can-merge, size/S, status/LGT1, dco-signoff: yes

#729 build: bump ti plugins to v1.8.3
  .prow.yaml
  configs/prow-dev/cluster/ti_community_autoresponder_deployment.yaml
  configs/prow-dev/cluster/ti_community_blunderbuss_deployment.yaml
  configs/prow-dev/cluster/ti_community_cherrypicker_deployment.yaml
  configs/prow-dev/cluster/ti_community_contribution_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_blocker_deployment.yaml
  configs/prow-dev/cluster/ti_community_label_deployment.yaml
  configs/prow-dev/cluster/ti_community_lgtm_deployment.yaml
  configs/prow-dev/cluster/ti_community_merge_deployment.yaml
  configs/prow-dev/cluster/ti_community_owners_deployment.yaml
  configs/prow-dev/cluster/ti_community_tars_deployment.yaml
  configs/prow-dev/cluster/tichi_web_deployment.yaml
Labels: status/can-merge, size/S, status/LGT1, dco-signoff: yes

#734 config: remove semantic pr title from required check
  configs/prow-dev/config/config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#735 config: skip-unknown-contexts for test-dev
  configs/prow-dev/config/config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#741 config: remove blockade from test-dev
  configs/prow-dev/config/external_plugins_config.yaml
  configs/prow-dev/config/plugins.yaml
Labels: status/can-merge, status/LGT1, dco-signoff: yes

#742 config: enable require_code_owner_reviews option for test-dev
  configs/prow-dev/config/config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#749 config: remove the required_approving_review_count
  configs/prow-dev/config/config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#750 Revert "config: remove the required_approving_review_count"
  configs/prow-dev/config/config.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes

#757 config: enable override plugins for test-dev
  configs/prow-dev/config/plugins.yaml
Labels: status/can-merge, size/XS, status/LGT1, dco-signoff: yes
